// Generated by CoffeeScript 1.10.0
(function() {
  var HomeDemo;

  HomeDemo = {
    init: function() {
      var $homeDemo, currentPage;
      $homeDemo = $('.home-demo');
      currentPage = '.facebook';
      $('.url-bar .dropdown-menu a', $homeDemo).on('click', function() {
        var $this, targetPage;
        $this = $(this);
        targetPage = $this.attr('data-targetpage');
        if (!targetPage) {
          targetPage = currentPage;
          return;
        }
        HomeDemo.changeDemoPage(targetPage);
        currentPage = targetPage;
        return $('.current-url').text($this.text());
      });
      $('.scan-button, .extension-button', $homeDemo).on('click', function() {
        var currentUrl;
        currentUrl = $('.current-url').text();
        $('.demo-center-action').removeClass('scan').addClass('scanning');
        $('.dropdown-toggle').prop('disabled', true);
        $('.extension-button').prop('disabled', true);
        return setTimeout(function() {
          $('.demo-center-action').removeClass('scanning').addClass('try-another');
          $('.dropdown-toggle').prop('disabled', false);
          $('.website .page' + currentPage + ' .place-name').addClass('highlight');
          $('.results .result').hide();
          return $('.results .result' + currentPage).show();
        }, 1500);
      });
      return $('.try-another-button', $homeDemo).on('click', function() {
        var $nextPage, nextPageSelector;
        $nextPage = $('.website .page' + currentPage).next();
        if ($nextPage.length === 0) {
          $nextPage = $('.website .page').first();
        }
        nextPageSelector = '.' + $nextPage.attr('class').split(' ')[1];
        HomeDemo.changeDemoPage(nextPageSelector);
        currentPage = nextPageSelector;
        return $('.current-url').text($('.url-bar .dropdown-menu a' + nextPageSelector).text());
      });
    },
    changeDemoPage: function(selector) {
      $('.website .content').scrollTop(0);
      $('.website .page .place-name').removeClass('highlight');
      $('.website .page').hide();
      $('.website .page' + selector).show();
      $('.demo-center-action').removeClass('try-another').addClass('scan');
      $('.extension-button').prop('disabled', false);
      $('.results .result').hide();
      return $('.results .empty').show();
    }
  };

  $(function() {
    return HomeDemo.init();
  });

}).call(this);
